### ISSUE TITLE
How to setup dev environment

### ISSUE THREAD

**Issue by hkfuertes** [Vito0912/abs_flutter#110]
Is there any guide on how to setup the dev environment? 

I wanted to try and add Android Auto support, but I'm not able to make it build as-is...

**Comment by Vito0912** [comment]
The build error has been resolved, and I have also added a Contribution.md file.

**Comment by Vito0912** [comment]
I've created an AndroidAuto branch in the repository: [AndroidAuto branch](https://github.com/Vito0912/abs_flutter/tree/feat/androidAuto).

Currently, this implementation would likely be rejected by Android since it lacks any substantial functionality beyond basic media control and seeking via Android Auto.

Next, I'll explore ways to pass data from Flutter to Android Auto to enhance its functionality and make it available to the Play Store.
