### ISSUE TITLE
Initiate Conversation

### ISSUE THREAD

**Issue by Dr-Blank** [Vito0912/abs_flutter#40]
Hello, I have just now discovered your project.

I did not find any discussion section hence I am creating an issue

please see https://github.com/Dr-Blank/Vaani if you have not already

I hope efforts are not wasted in building duplicate apps, lets talk if you are okay.

**Comment by Vito0912** [comment]
Hello,

Your work looks fantastic! I appreciate the effort you've put in. 
However, I believe we might have slightly different objectives for the goal of the app (proramming wise and platform wise). My goal is to ensure full platform support (Android, Windows, ..., browser compatibility, including features like downloads and more.)

Additionally, I plan to generate routes entirely via OpenAPI. Given that API routes will change in the near future, as sometime previously announced, this approach will make it easier to integrate new features swiftly and efficiently.

My aim is to make the application accessible on as many platforms as possible. 

However, I will need to take a brief break (only a few weeks at most) due to other commitments. (Thats why there is no update lately)

I really admire your app’s design! 
However, I want to point out that there are other Flutter apps built with similar platform targets and routing methods (althougt the design is not near that good as of yours). I mention this not to discourage you, but to explain why I decided to create my own app rather than contribute to an existing one.
Also I try to be near the ABS branding - I want to stress that it is a client FOR ABS.

My goal is to build a highly modular app that allows for easy addition of new routes with proper typing, optimized for speed, and featuring extensive caching support—on the interceptor layer. I'm also exploring some unconventional approaches, such as providing logs to users directly through the UI or giving the user pretty much control over everything.

I would be happy to explore potential collaboration opportunities. I've opened the discussions tab for this purpose.

**Comment by Dr-Blank** [comment]
Thank you for the words of encouragement. This is my first project in flutter so yes there are a lot of inconsistencies and a lot to learn, I was playing with your app and was astounded at how much you achieved in such less time, it's commendable.

I wanted to use an openapi generator for my project as well but abs didn't have the spec.json at the time so went with whatever was available. I will be migrating to openapi once support comes. I will have to study how you managed to get the api spec.

And yes my goal is also to support all the platforms that flutter support, that was the reason I went with flutter in the first place.

I just wanted to share a link so that none of us reinvents the wheel. 

Cheers

**Comment by Vito0912** [comment]
@Dr-Blank 
Yeah!
I also noticed that you're using only one design. As mentioned before, the design looks awesome (and maybe there will be some inspiration - the player controls look great).

However, I noticed that you're using only Material Design. While this works for Android, iOS users often have completely different design expectations. This makes it harder to create a universal design, because a function that works well with Android/Material Design can be entirely different in iOS.

Just so you know BUT , my app doesn't work with iOS either currently, due to the widget tree, but it theoretically works with iOS-style widgets (Cupertino).

I'm not a professional at all (actually just a student who had some free spare time, which is why I currently need to take off a week or so to reorganize and then work slowly on the app). I'm focusing more on functionality than design (okay, it's just an excuse because I can't make nice UIs! 😄)

Here are a couple of examples you might want to look at:

https://github.com/keaganhilliard/audiobookly (I haven't tested it as it's currently not building for me)
https://github.com/RasmusKoit/abs_wear

I also added you via Discord :) 
And thank you very much.

I also would recommend to add a feature page to your Project. I currently cannot test it, but currently it looks to me that it does not support podcasts etc. 
But it is the first "bigger" project for me too (build flutter apps since 4,5 years, but never professionally)
