### ISSUE TITLE
Can the Windows version of the application provide a tray minimize feature?

### ISSUE THREAD

**Issue by GrayGuardian** [Vito0912/abs_flutter#44]
There is also a tray menu feature for switching between chapters in audiobooks, similar to the previous and next track functionality in music.

This is very helpful for me when I'm slacking off at work. Thank you!

**Comment by Vito0912** [comment]
Could you clarify what you mean? Are you looking to minimize the application so that it only appears in the system tray (accessible in the bottom-right corner of the taskbar) and not in the taskbar itself?

Thank you!

**Comment by Vito0912** [comment]
I've added a tray that allows you to pause, skip, and jump between chapters. I hope this aligns with what you had in mind.

The release will be available until a new version of the Audiobookshelf server is released, as I've removed a setting that will only be replaced in the upcoming version.

Tip: Instead of editing your message after a response, it’s best to send a new one, as edited messages don’t trigger notifications.

**Comment by Vito0912** [comment]
Now is live when the build finishes
