### ISSUE TITLE
Chinese language pack

### ISSUE THREAD

**Issue by GrayGuardian** [Vito0912/abs_flutter#47]
Thank you for your help yesterday. I am currently communicating with you through AI translation.

If permitted, can a Chinese language pack be added to the application?

Thank you!

**Comment by Vito0912** [comment]
All translations for the project are managed through Weblate: https://hosted.weblate.org/projects/audiobookshelf-flutter-client/app/

Since I don’t speak Chinese myself, I can add Chinese as a language on the platform, but you would need to handle the translations. Currently, I’m using Weblate’s free trial, which expires in 4 days. After that, we’ll need to add translations directly via file access, as I believe this project may be too small to receive extended approval.

If you’d like to proceed, I can help set up everything on my end. Could you let me know which specific Chinese language variant you’d like (e.g., Simplified, Traditional)? There are quite a few options.
Like Hakka, Min Nan, etc. Etc. (I don’t know exactly in what they differ but I can select them all for Chinese)

I hope you can easily translate that.

**Comment by GrayGuardian** [comment]
Just provide Simplified Chinese, and I believe this app will have a large user base in China. So how can I help you translate into Simplified Chinese?"

**Comment by Vito0912** [comment]
It looks like you’ve successfully added a new language - that’s good! Unfortunately, I can’t assist much with translation beyond using an automatic translator, which may not be ideal for accuracy. Hopefully, you’re able to translate some of the key phrases yourself.

When you’re ready for me to add the new language to the app and prepare a new release, just leave a comment to let me know!
