### ISSUE TITLE
[FEATURE REQUEST] Make Series-Tab searchable and sortable

### ISSUE THREAD

**Issue by kuldan5853** [Vito0912/abs_flutter#88]
Similar to the other reported bug where collapsing series does nothing, the library sorting A-Z option also does nothing, the series etc. still end up in random order.

**Comment by Vito0912** [comment]
Could you clarify the issue further? Sorting by title seems to work correctly for both series and the library view on my end.

However, please note that sorting while performing a search is currently not possible due to limitations with ABS. That said, I'll make sure to add a note/reset the search indicating that sorting isn't available when a sort option is invoked during a search.
Also collapse series is currently expected to not work

**Comment by kuldan5853** [comment]
Hi - I enabled the setting "Sort series in Ascending Order", then go to the Series tab (no matter if the app was restarted in between), and the series are still in random order (in my case at the moment it is T, T, T, S, O, M, I, F, E, D, D, D, D, D, T, T, S, O, ... etc. 

I think the best would be an actual button for the sort order (ascending/descending) on the series tab itself (same for authors, collections..)

**Comment by Vito0912** [comment]
Ah, I see where the confusion might be. This switch works differentlyu. You can freely choose which attribute to sort by—just use the button located right next to the search bar. (Note that searching isn’t available in the series view, which is why the feature is disabled there.)

The setting you mentioned only determines the default sorting order: whether it sorts in ascending order (1, 2, 3, 4…) or descending order (…, 4, 3, 2, 1) for the sequence of the series, not name.

I added this feature because I personally prefer the default sorting to be descending (…, 4, 3, 2, 1), but I know others prefer ascending (1, 2, 3, 4).

**Comment by kuldan5853** [comment]
Okay, that makes sense...but there is no search bar on the "series" tab? Only on the "Library" tab. 

I always hit the "statistics" button by accident because to me it looks like it would be for sorting instead..

**Comment by Vito0912** [comment]
I reopened the issue. I understood you in the wrong way.
I will look into it if this is possible with the current API

**Comment by kuldan5853** [comment]
> I reopened the issue. I understood you in the wrong way. I will look into it if this is possible with the current API

Just to put it out there, as ISO-B and I are working on a similar thing in the official app for Android Auto - client side sorting is also a possibility, at least if it's only about sorting random, ascending, descending for Series.

**Comment by Vito0912** [comment]
If I remember correctly, I use pagination for the series view, so implementing client-side scrolling would result in unexpected behavior when scrolling down/loading more.
But I think you can have a filter (aka searching functionality). I will try implementing that today

**Comment by Vito0912** [comment]
I've implemented a search feature for the series and plan to publish it in the coming days once I've also added the functionality to collapse the series.
The search functionality shares its "memory" with the library search bar. This means that if you search for a series in the library and then switch to the series view, the search is retained, instantly displaying the relevant series. However, should I instead clear the search when transitioning to the series view?

**Comment by kuldan5853** [comment]
Hey, I just updated to 1.6.7 to test this out - the search bar shows up, but the sorting does absolutely nothing, no matter what I select, it stays the same unsorted order than before - in fact, selecting any of possible options on the search bar and toggling it asc or desc does exactly nothing.

**Comment by Vito0912** [comment]
I knew I forgot something, shit.

**Comment by Vito0912** [comment]
This new PR should be finally fixed now.
I disabled filtering for series (as it is not needed) and added all supported sorting options.
I excluded the search from caching as it just would use a lot of disk space. So searching could be slower.
It will be available as a release in about 15 minutes and in playstore in about 30 to 45 minutes
